apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pulceo-resource-manager

spec:
  rules:
    - http:
        paths:
          - path: /api/v1/nodes
            pathType: Prefix
            backend:
              service:
                name:  pulceo-resource-manager
                port:
                  number: 7878
          - path: /api/v1/links
            pathType: Prefix
            backend:
              service:
                name: pulceo-resource-manager
                port:
                  number: 7878
          - path: /api/v1/providers
            pathType: Prefix
            backend:
              service:
                name: pulceo-resource-manager
                port:
                  number: 7878
          - path: /api/v1/resources
            pathType: Prefix
            backend:
              service:
                name: pulceo-resource-manager
                port:
                  number: 7878
          - path: /api/v1/tags
            pathType: Prefix
            backend:
              service:
                name: pulceo-resource-manager
                port:
                  number: 7878
          - path: /prm/health
            pathType: Exact
            backend:
              service:
                name: pulceo-resource-manager
                port:
                  number: 7878

---
apiVersion: v1
kind: Service
metadata:
  name: pulceo-resource-manager

spec:
  ports:
    - protocol: TCP
      name: web
      port: 7878
  selector:
    app: pulceo-resource-manager

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulceo-resource-manager
  labels:
    app: pulceo-resource-manager

spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulceo-resource-manager
  template:
    metadata:
      labels:
        app: pulceo-resource-manager
    spec:
      containers:
        - name: pulceo-resource-manager
          image: ghcr.io/spboehm/pulceo-resource-manager:v1.3.0
          imagePullPolicy: Always
          volumeMounts:
            - name: prm-pv-db
              mountPath: /db
          env:
            - name: PRM_HOST
              valueFrom:
                configMapKeyRef:
                  name: prm-configmap
                  key: PRM_HOST
            - name: PMS_HOST
              valueFrom:
                 configMapKeyRef:
                   name: prm-configmap
                   key: PMS_HOST
            - name: PSM_HOST
              valueFrom:
                configMapKeyRef:
                  name: prm-configmap
                  key: PSM_HOST
            - name: PNA_MQTT_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: prm-credentials
                  key: PNA_MQTT_BROKER_URL
            - name: PNA_MQTT_CLIENT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: prm-credentials
                  key: PNA_MQTT_CLIENT_USERNAME
            - name: PNA_MQTT_CLIENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prm-credentials
                  key: PNA_MQTT_CLIENT_PASSWORD
            - name: PNA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: prm-credentials
                  key: PNA_USERNAME
            - name: PNA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prm-credentials
                  key: PNA_PASSWORD
            - name: PNA_INIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: prm-credentials
                  key: PNA_INIT_TOKEN
          ports:
            - containerPort: 7878
              name: web
      volumes:
        - name: prm-pv-db
          persistentVolumeClaim:
            claimName: prm-pv-db

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prm-pv-db
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
